# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Pushes test folder
      uses: https://github.com/Chetanby/cicd-testing@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'test'
        destination_repo: 'Chetanby/cicd-testing-destination@master'
        destination_folder: 'test'
        user_email: 'chetu.by@gmail.com'
        user_name: 'Chetanby'
        commit_msg: '[GHA] Update the test files.'
